### ISSUE TITLE
我发现了一个bug

### ISSUE THREAD

**Issue by tower111** [h0mbre/CTP#1]
https://github.com/h0mbre/CTP-OSCE/blob/090b035c3d8c63b20750a3a2e28871589b1ca842/Boo-Gen/boo-gen.py#L66

你好，

`POST /cgi-bin/wan.cgi HTTP/1.1
Host: 192.168.8.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: text/plain, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://192.168.8.1/wan.html
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 138
Origin: http://192.168.8.1
Connection: close

{"task_id":"3.2","proto":"3","ipaddr":"192.168.8.2","netmask":"255.255.255.0","gateway":"192.168.8.254","dns1":"2.2.2.2","dns2":"2.2.2.3"}`
当我尝试用上面这个包fuzz的时候出现了错误。
`\Boo-Gen>python boo-gen.py test.txt --post -f fuzz.py
Traceback (most recent call last):
  File "boo-gen.py", line 159, in <module>
    post()
  File "boo-gen.py", line 83, in post
    second = x.split("=")[1]
IndexError: list index out of range`
应该事json串处理的问题，希望您能够解决，感谢

**Comment by santhoshn16** [comment]
A new line character is seen at the end of test.txt while I have tried printing it. To successfully run the code just change list2 = contents.split("\n")[-1] to list2 = contents.split("\n")[-2]

**Comment by zhjygit** [comment]
> A new line character is seen at the end of test.txt while I have tried printing it. To successfully run the code just change list2 = contents.split("\n")[-1] to list2 = contents.split("\n")[-2]

no use

**Comment by zhjygit** [comment]
![image](https://user-images.githubusercontent.com/44870751/206113945-f5e7d1dd-79aa-4857-b322-79a7e5b2d30a.png)
另外，在执行时一般都会报错，错误地转义无法执行，主要是符号"，转换后变成了s_string(" "xxx" ")，正确的应该是s_string(" 'xxx' ")。需要手动修改，但代码如何优化呢？

使用了boofuzz（一个burpsuite插件），也会出现这种问题。
